export enum DiagramType {
  Mermaid = 'MermaidDiagram',
  Mindmap = 'MindmapDiagram',
  Pie = 'PieDiagram',
  Flowchart = 'FlowchartDiagram',
  Sequence = 'SequenceDiagram',
  Journey = 'JourneyDiagram',
  Requirement = 'RequirementDiagram',
  Gantt = 'GanttDiagram',
  Timeline = 'TimelineDiagram',
  Quadrant = 'QuadrantDiagram',
  Sankey = 'SankeyDiagram',
  Xychart = 'XYChartDiagram',
  Packet = 'PacketDiagram',
  Kanban = 'KanbanDiagram',
  Block = 'BlockDiagram',
  Architecture = 'ArchitectureDiagram',
  Class = 'ClassDiagram',
  State = 'StateDiagram',
  Er = 'ERDiagram',
  Git = 'GitDiagram',
  C4 = 'C4Diagram',
}

export enum MermaidDescriptionName {
  Mermaid = 'mermaid',
  Mindmap = 'mindmap',
  Pie = 'pie',
  Flowchart = 'flowchart',
  Sequence = 'sequenceDiagram',
  Journey = 'journey',
  Requirement = 'requirementDiagram',
  Gantt = 'gantt',
  Timeline = 'timeline',
  Quadrant = 'quadrantChart',
  Sankey = 'sankey-beta',
  Xychart = 'xychart-beta',
  Packet = 'packet-beta',
  Kanban = 'kanban',
  Block = 'block-beta',
  Architecture = 'architecture-beta',
  Class = 'classDiagram',
  State = 'stateDiagram-v2',
  Er = 'erDiagram',
  Git = 'gitGraph',
  C4 = 'C4Context',
}

export enum MermaidLanguageType {
  Mermaid = 'mermaid',
  Mindmap = 'mindmap',
  Pie = 'pie',
  Flowchart = 'flowchart',
  Sequence = 'sequence',
  Journey = 'journey',
  Requirement = 'requirement',
  Gantt = 'gantt',
  Timeline = 'timeline',
  Quadrant = 'quadrant',
  Sankey = 'sankey',
  Xychart = 'xychart',
  Packet = 'packet',
  Kanban = 'kanban',
  Block = 'block',
  Architecture = 'architecture',
  Class = 'class',
  State = 'state',
  Er = 'er',
  Git = 'git',
  C4 = 'c4',
}

export enum MermaidAlias {
  Graph = 'graph',
  Sequence = 'sequence',
  Requirement = 'requirement',
}
